### PR TITLE
Update/Fixes

### PR DESCRIPTION
**Pull request by arij**
- Update BOM
- Fix pin mappings

### CODE REVIEW

**Comment by mohitg11** [comment]
Hi, 

I see one is a part for part replacement, the other one, what were the changes?

**Comment by arij** [comment]
Hey,

The part which you originally choose seems to be unavailable everywhere.
The new part is more easily attainable. The data sheets are identical.

**Comment by mohitg11** [comment]
Understood that, I was wondering about the other change that was done, fixed pin mapping.

**Comment by arij** [comment]
The pins between usb connectors for each half did not line up to each other
(for RGB, ledan, and ledcath). The pins have been rearranged on the right
half connector, in PCB design and schematic. The changes were: Move
RGBLDOUT to where LEDAN is, move LEDCATH to where RGBLDOUT is, and move
LEDAN to where LEDCATH is, on the left half only. This matches pins on
right side now.

**Pull request merged**
